### ISSUE TITLE
Canon Facets

### ISSUE THREAD

**Issue by Jigarsolanki** [rackerlabs/canon-react#55]

**Comment by jdrush89** [comment]
PR https://github.com/jdrush89/canon-react/pull/1

This PR adds 4 components: FacetSection, Facet, Criteria, and FacetToggler.
FacetSection:
Renders the facet header and individual facet components.
Relies on a facetData object to generate facet components.  The object should be in the form:
```
{facetLabel: 
  {criteriaLabel: {count: number, iconClass: string, filter: func, disabled: opt_bool, hidden: opt_bool}}
}
```
For example:
```
facetData = {
      'TAGS': {
        'Engineering': {count: 8, filter: () => {}, disabled: true},
        'Sales': {count: 2, filter: () => {}},
        'Finance': {count: 0, filter: () => {}, hidden: true}
      },
      'STATUS': {
        'Error': {count: 2, filter: () => {}, iconClass: 'rs-status-error'},
        'Rebooting': {count: 3, filter: () => {}, iconClass: 'rs-status-warning'},
        'Active': {count: 5, filter: () => {}, iconClass: 'rs-status-ok'}
      }
    };
```
The FacetSection maintains the selected facets as state in an object of the same form.  When the selection changes, it fires a callback to its parent with the crtieria/facet labels and the filter function.

Facet:
This component renders a header and a list of criteria.  It expects a criteria object and selected criteria object, both in the form
```
{criteriaLabel: {count: number, iconClass: string, filter: func, disabled: opt_bool, hidden: opt_bool}
```
It will create criteria components from these objects, passing in the object values as props.  Facets truncate the list of criteria to 5 (by default) and display a FacetToggler to expand/collapse the list.  They also render a clear link when a criteria is selected that will clear all selections.

Criteria:
Criteria render a label and optional count in the form 'label (count)'.  They can be hidden, disabled, or given an icon class through props.  When clicked, they trigger a selection changed callback that should be used to apply the filter function associated with that criteria.

FacetToggler:
A simple link with arrow displaying '> more' or 'less ^'.  Triggers a toggle callback when clicked that should be used by a Facet to expand/collapse a list of criteria.

**Comment by jdrush89** [comment]
There are two significant changes from this design I brought up in the PR and wanted to make a note of here.  I think it may be best to move the selected state out of the FacetsSection.  It will remove state from the component which makes it simpler, and encourages a single source of truth for the selected state (instead of having the selected filters being maintained outside and the state inside and tying to keep them in sync).

The second issue is how the data is passed in.  Instead of passing one object with all the data, I think it will be better to render each component with data passed in as props.  So instead of 
```
<FacetsSection data={facetData} />
```
I would do
```
<FacetsSection>
  <Facet label={"TAGS"}>
    <Criteria label={"Development"} count={facetData['TAGS']['Development'].count} filter={facetData['TAGS']['Development'].filter} />
  </Facet>
</FacetsSection>
```
This is more declarative and reduces the nesting of the components, which makes them simpler to test as well as allowing users to wrap them with their own criteria/facet components to extend the functionality.

The downside to both of these changes is they will require more code around the facets to make them functional.

**Comment by bradgignac** [comment]
@MACSkeptic Will this work for Janus?

**Comment by adampickeral** [comment]
@MACSkeptic @bradgignac bump. would love to get some feedback on this from another team that needs faceting

**Comment by MACSkeptic** [comment]
the overall idea is very similar to what we implemented on janus (just done better here : ))

I left some comments on the PR, but I couldn't see anything on this that would be a deal breaker for us just using it.

I'd like to see the values that facet/criteria are keyed off of being not the label but an arbitrary value provided as a prop together with the label. That would probably save some mapping code for whoever uses this.

**Comment by jdrush89** [comment]
@MACSkeptic Thanks for the feedback!  I've addressed all the review comments.  Let me know if it looks :ship:able
