### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by adampickeral** [rackerlabs/canon-react#8]
## Proposed Design

```jsx
  <Tooltip content={(This is my <strong>content</strong>)}>
    <Button>Save</Button>
  </Tooltip>
```

* `content` will accept some react component(s) and render it in the body of the tooltip.
* the `Tooltip` component will add a hover handler to its child element and control the display of the tooltip
* tether will be used for positioning

**Comment by adampickeral** [comment]
@jdrush89 thoughts?

**Comment by j00k** [comment]
what happens if you have multiple children of the tooltip

**Comment by willcumbie** [comment]
I don't like the idea of a list of targets. Finding a workable format to pass them in through is tricky. It's not hard to validate that a tooltip should only have one child, and i don't think attaching to multiple elements is a very common case. (Can you think of any big examples?)

**Comment by j00k** [comment]
@willcumbie:

can you explain what's difficult about passing props?

why enforce only one child?

the most prolific tooltip we use on reach is the "disable due to rbac" tooltip. would be nice to not need a different tooltip rendered for each item.

**Comment by j00k** [comment]
maybe we can take some inspiration from react-bootstrap one this one

**Comment by willcumbie** [comment]
@j00k Because in order to have something to pass in, you have to already have rendered them. If you want the tooltip to be a sibling of the element it's attached to, you're hosed. You can't have a reference to a particular element on the page until it's been rendered onto the document, so passing around references to them can't happen until rendering occurs. Which means more complexity in the lifecycle, because you have to wait for the render to finish in order to pass it to the tooltip, etc.

I feel like I must be misunderstanding what you're suggesting, because what you're suggesting doesn't make any sense to me at all.

React-Bootstrap does it in a similar way:
http://react-bootstrap.github.io/components.html#tooltips
Instead of one tooltip component, they split the logic into two parts--the tooltip itself and the OverlayTrigger which handles binding it to an element. I think that's overkill (especially since our tooltips don't have those little arrows), but it's within reason. Kept the same is the idea that attaching the tooltip should be handled by a parent component that attaches it to its child.

**Comment by bradgignac** [comment]
It seems like a pretty huge limitation to pass HTML instead of using JSX. Why not treat it like a popover where you can a have a trigger that references an instance of a Tooltip and maintain consistent React behavior all the way down?

**Comment by bradgignac** [comment]
Using HTML also prevents the use of shared components inside a tooltip, right?

**Comment by bradgignac** [comment]
Ignore me. I think I get it now. Just need to make sure tooltips are rendered into a separate tree.

**Comment by j00k** [comment]
@willcumbie i do prefer the react-bootstrap example there

**Comment by adampickeral** [comment]
this is actually meant to closely follow the react-bootstrap example. i should have named things better in the example above. it would look more like this:

```jsx
<TooltipTrigger content={(This is my <strong>content</strong>)}>
    <Button>Save</Button>
  </TooltipTrigger>
```

`content` takes jsx, so it could take a custom component, or in the example just simple html. The trigger would render a `Tooltip` component on hover/focus of its child, and the content prop would be rendered into the body of the `Tooltip` component.

**Comment by jdrush89** [comment]
Do we want the current reach behavior where tooltips display on the mouse cursor's position?  It should be doable with tether, but might be tricky to get the offset right.

**Comment by adampickeral** [comment]
@jdrush89 that's a good question that I'm struggling with right now. it is proving pretty complicated to get the tooltip to display at the mouse cursor's position. the actual tooltip library created by tether, and bootstrap tooltips all are rendered at a fixed position relative to the target instead of the mouse cursor.

canon doesn't really advise on the positioning of the tooltip, and i see a mix of behavior on the canon docs site where the example tooltip is rendered at a fixed position relative to the target, but other tooltips on the page are rendered at the mouse cursor position.

it's certainly easier to just pick a position and render it there (or let the consumer decide). @bradgignac what's your take? do you know any history about how tooltips should be positioned?

**Comment by bradgignac** [comment]
Position it relative to the element, not the mouse. :)

**Comment by adampickeral** [comment]
Tooltip implementation here: https://github.com/rackerlabs/canon-react/pull/36
review please!

**Comment by adampickeral** [comment]
merged
